name: ogcrl
channels:
  - conda-forge
  - nvidia
  - nodefaults
dependencies:
  - python 3.11.*
  - numpy <2
  - cuda-nvcc *
  - pip
  - cudnn=8.9
  - pip:
    - --index-url https://pypi.org/simple/
    - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    - -e .
    - chex==0.1.87
    - distrax==0.1.5
    - dm-control==1.0.27
    - flax==0.9.0
    - gym==0.24.1
    - gymnasium==1.0.0
    - lockfile==0.12.2
    - matplotlib==3.9.2
    - ml-collections==0.1.1
    - moviepy==1.0.3
    - optax==0.2.2
    - shapely==2.0.6
    - shimmy[gym-v21gym-v26]>=0.2.1
    - wandb>=0.19.11
    - jax==0.4.28
    - jaxlib==0.4.28+cuda12.cudnn89
    - nvidia-cusolver-cu12==11.7.5.82
    - nvidia-cuda-cupti-cu12==12.9.79
